dist: trusty
sudo: false
language: php

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
php:
    - 7.2
    - 7.3

env:
    - TEST_COLLECTION=collection-1x.json EZVERSION=1.13.*
    - TEST_COLLECTION=collection-2x.json EZVERSION=2.*

matrix:
    include:
        - php: 7.2
          env: TEST_COLLECTION=collection-2x.json EZVERSION=2.* EXECUTE_DEPLOYMENT=true
    exclude:
        - php: 7.2
          env: TEST_COLLECTION=collection-2x.json EZVERSION=2.*

before_install:
    - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_TAG != '' ]]; then openssl aes-256-cbc -K $encrypted_91e9470aafb9_key -iv $encrypted_91e9470aafb9_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d; fi
    - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_TAG != '' ]]; then tar xvf .travis/secrets.tar -C ./ ; fi
    - phpenv config-rm xdebug.ini
    - composer self-update

install:
    - travis_retry composer install --no-interaction
    - composer info -i
    - docker pull postman/newman_ubuntu1404:latest

script:
    - php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php src/
    - php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php tests/Tests/
    - php vendor/bin/phpunit -c tests/ --exclude-group behat
    - php vendor/behat/behat/bin/behat -c tests/behat.yml
    - php bin/ez-prod init ezsystems/ezplatform $EZVERSION --no-interaction -vvv
    - php bin/ez-prod ps
    - rm -rf ezplatform/var/cache && rm -rf ezplatform/app/cache && docker run --net=host -v $(pwd)/tests/postman:/etc/newman -t postman/newman_ubuntu1404 run $TEST_COLLECTION

after_success:
    - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_TAG != '' ]]; then curl -LSs https://box-project.github.io/box2/installer.php | php ; fi
    - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_TAG != '' ]]; then chmod 755 box.phar ; fi
    - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_TAG != '' ]]; then ulimit -Sn 4096 ; fi
    - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_TAG != '' ]]; then php -d "phar.readonly=false" ./box.phar build -vv ; fi

deploy:
    provider: releases
    api_key:
        secure: dakhsd0cboNkSTiY9agURbETI/Lj4rzPvTEl2l/F/PUedm+HRcueT1/dQwkXpoYwnoD/xBsllv/7FfTpZDiK9Im0APeqUDRQ1cp7ZxXth9TRsIvaPf8adDLGGe87wz/sdBUvrlhs5KhqZnHNsVBhUfki0z1EsLb6lW9DmS8mU+5bjYMki4FZi0feBq0wnF4d27aN5RqoE8tbJOssT2y7cMc0/taxOTNrFUzC4bphMTONHhrNUsmfcA5olki6fePg0lb2uG7uD9sjl0Hyy9Fy9gUjMhVe6rRnW2E7svVgcTwgldYjbYruwbeyWusRBac65QwyOlSp6ZoE3iawh+c5FIDHFuSw9joryGJ5cLAlybxn4Ki7bmLdX7NSc9nBlWAVYGlwfUPRKZ3Kidku6/NSxl+hENHZm8C8J/jW+YedabNcBy56x6ikJnvP0KmZNCfyKPys1Zy3GQ4NzXSP/iKuKqy1f6F3HilrK6ab3lxZ8ofDfKjhgz54t5AkCV4lJP1Wq+wB2G1PNXXmMJ8f1MLMLxlsC5Xc5FBWHYZUs2umscAY1EkblEJelcDZ83GddZmrwovvfku9H9ai/HbXQlsux3CPYjW9NyfhYsrNc/FjNWsGp0tpHk4Cp0t6qNih5xdJR7cWIkQoB27/eX7onia+yNZOyVaxTScDc0idCtcdqSk=
    file: ez.phar
    skip_cleanup: true
    on:
        tags: true
        php:  '7.2'
        repo: ezsystems/launchpad

notifications:
    email: false
