---
parameters:
    github_release_url: "https://api.github.com/repos/ezsystems/launchpad/releases?draft=false&prerelease=false"

services:

    _defaults:
        autowire: true
        public:  true

    eZ\Launchpad\Listener\ApplicationUpdate:
        arguments:
            - {release_url: "%github_release_url%"}
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    eZ\Launchpad\Listener\CommandException:
        tags:
            - { name: kernel.event_listener, event: console.error, method: onExceptionAction }

    eZ\Launchpad\Listener\CommandStart:
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }


    eZ\Launchpad\Listener\CommandTerminate:
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminateAction }

    eZ\Launchpad\Core\ProjectStatusDumper: ~

    eZ\Launchpad\Listener\OSXListener:
        class:
        arguments: [!tagged ezlaunchpad.osx.optimizer]
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    # OSX OPTIMIZER
    eZ\Launchpad\Core\OSX\Optimizer\D4M:
        tags: [ezlaunchpad.osx.optimizer]

    eZ\Launchpad\Core\OSX\Optimizer\NFSVolumes:
        tags: [ezlaunchpad.osx.optimizer]
