---
parameters:
    ez_phar: 'https://ezsystems.github.io/launchpad/ez.phar'
    ez_phar_version: 'https://ezsystems.github.io/launchpad/ez.phar.version'

services:

    _defaults:
        autowire: true
        public:  true

    eZ\Launchpad\Listener\ApplicationUpdate:
        arguments:
            - {env: "%app_env%", dir: "%app_dir%", url: "%ez_phar%", version: "%ez_phar_version%"}
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    eZ\Launchpad\Listener\CommandException:
        tags:
            - { name: kernel.event_listener, event: console.error, method: onExceptionAction }

    eZ\Launchpad\Listener\CommandStart:
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }


    eZ\Launchpad\Listener\CommandTerminate:
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminateAction }

    eZ\Launchpad\Core\ProjectStatusDumper: ~

    eZ\Launchpad\Listener\OSXListener:
        class:
        arguments: [!tagged ezlaunchpad.osx.optimizer]
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    # OSX OPTIMIZER
    eZ\Launchpad\Core\OSX\Optimizer\D4M:
        tags: [ezlaunchpad.osx.optimizer]

    eZ\Launchpad\Core\OSX\Optimizer\NFSVolumes:
        tags: [ezlaunchpad.osx.optimizer]
